### ISSUE TITLE
Giant Gram 2000, Giant Gram: All Japan Pro Wrestling 2 (NAOMI)

### ISSUE THREAD

**Issue by TheCoolPup** [blueminder/flycast-netplay-savestates#10]
[gram2000.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7499967/gram2000.state.zip)
[ggram2.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7499974/ggram2.state.zip)

**Comment by TheCoolPup** [comment]
Save states for the Giant Gram games on the NAOMI Board. Inside the zips are the .net files. :)

**Comment by blueminder** [comment]
Added. Thanks!

https://github.com/blueminder/flycast-netplay-savestates/commit/ee51e292e8e24691f3fa0d6c9c31c0ca9c24aa46
