### ISSUE TITLE
Dirty Pigskin Football, Dolphin Blue

### ISSUE THREAD

**Issue by TheCoolPup** [blueminder/flycast-netplay-savestates#12]
[dolphin.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7507848/dolphin.state.zip)
[dirtypig.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7507850/dirtypig.state.zip)

**Comment by TheCoolPup** [comment]
Inside the zips are save states for Dirty Pigskin Football, and Dolphin Blue. Both on the Atomiswave system. :)

**Comment by blueminder** [comment]
Tested and added. Thank you!
