### ISSUE TITLE
Enable gamepad for Cyber Troopers - Virtual-On - Oratorio Tangram (USA)

### ISSUE THREAD

**Issue by Ken1f** [blueminder/flycast-netplay-savestates#16]
[Cyber Troopers - Virtual-On - Oratorio Tangram (USA).state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7664133/Cyber.Troopers.-.Virtual-On.-.Oratorio.Tangram.USA.state.zip)

**Comment by blueminder** [comment]
Tested and added. Thank you!
