### ISSUE TITLE
Tech Romancer Save State

### ISSUE THREAD

**Issue by crowspaceboy** [blueminder/flycast-netplay-savestates#17]
I have not been able to connect with anyone in Tech Romancer despite having the same rom and save states as players I'm connecting with. I've also noticed that there have been no tech romancer games since Nov of last year, and most (but not all) of Tech Romancer's replays have been broken. After talking with blueminder, there is a possibly that there is a larger issue with Tech Romancer's save state, so I'm uploading my local save state for testing purposes. I hope this helps!
[Tech Romancer (USA).state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7901003/Tech.Romancer.USA.state.net.zip)

**Comment by blueminder** [comment]
When I try to load this savestate, I keep getting unhandled SH4 errors. What changes were made to make this savestate? I might try to recreate it myself since this one doesn't seem to be working.

**Comment by blueminder** [comment]
New savestate tested and uploaded.
