### ISSUE TITLE
Virtual On Oratorio Tangram - Enable music & timer. Everything unlocked. Updated VMU with VOOT save

### ISSUE THREAD

**Issue by Ken1f** [blueminder/flycast-netplay-savestates#19]
[Cyber Troopers - Virtual-On - Oratorio Tangram (USA) + VMU.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7970451/Cyber.Troopers.-.Virtual-On.-.Oratorio.Tangram.USA.%2B.VMU.zip)

**Comment by blueminder** [comment]
All set! Thank you!
