### ISSUE TITLE
Virtua Fighter 4 EVO Save State

### ISSUE THREAD

**Issue by DarkTetrad** [blueminder/flycast-netplay-savestates#20]
Set to 3 rounds, 45 seconds, stage select on
[vf4evoct.state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7986739/vf4evoct.state.net.zip)

**Comment by DarkTetrad** [comment]
With Free Play on 
[vf4evoct.state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7986800/vf4evoct.state.net.zip)

**Comment by blueminder** [comment]
Thank you! It should be in now.
