### ISSUE TITLE
Sega Tetris (NAOMI)

### ISSUE THREAD

**Issue by TheCoolPup** [blueminder/flycast-netplay-savestates#21]
savestate for Sega Tetris
[sgtetris.state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7988605/sgtetris.state.net.zip)

**Comment by blueminder** [comment]
I was unable to load this savestate. Please make sure you are using the latest stable version of Flycast Dojo that is included with Fightcade when you are generating states (0.4.22 at the time of writing).
