### ISSUE TITLE
Virtual On Oratorio Tangram - Fixed previous corrupted save state

### ISSUE THREAD

**Issue by Ken1f** [blueminder/flycast-netplay-savestates#22]
[Cyber Troopers - Virtual-On - Oratorio Tangram (USA).state.net + VMU FIXED.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8084572/Cyber.Troopers.-.Virtual-On.-.Oratorio.Tangram.USA.state.net.%2B.VMU.FIXED.zip)

**Comment by blueminder** [comment]
Just updated the savestate. Thanks again.
