### ISSUE TITLE
Bust-A-Move 4/Puzzle Bobble 4 (DreamCast) Save State

### ISSUE THREAD

**Issue by HoxNorf** [blueminder/flycast-netplay-savestates#31]
Save State for Bust-A-Move 4/Puzzle Bobble 4 on DreamCast starting at the character select screen with options on default and all characters unlocked.
[Bust-A-Move 4 (USA).state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8295507/Bust-A-Move.4.USA.state.net.zip)

**Comment by blueminder** [comment]
Tested and works. Just added. Thank you!
