### ISSUE TITLE
King of Fighters 99 Evolution (Dreamcast)

### ISSUE THREAD

**Issue by Khalil78-eng** [blueminder/flycast-netplay-savestates#32]
Savestate for King of Fighters 99 Evolution (USA)
[King of Fighters, The - Evolution (USA) (En,Ja,Es,Pt).state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8306985/King.of.Fighters.The.-.Evolution.USA.En.Ja.Es.Pt.state.net.zip)

**Comment by blueminder** [comment]
Tested and added. Thank you!
