### ISSUE TITLE
Power Stone pstone Updated Netplay Savestate to Remove Censorship

### ISSUE THREAD

**Issue by MidoriHoshi** [blueminder/flycast-netplay-savestates#40]
This updated savestate for pstone netplay removes the censorship in the current file thanks to changing the region to Japan. All of the other settings are the same as before. The three differences are: Falcon's name was changed back to the original Fokker name, slashing attacks have a blood effect, and the character Rouge when transformed will have more skin visible on her breasts.

There are no downsides to having the game set to the Japan region for VS mode. The voices and text when playing are exactly the same as before with the exception of the name change for Falcon / Fokker.

[pstone.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8308624/pstone.state.zip)

**Comment by blueminder** [comment]
Updated. Thank you!
