### ISSUE TITLE
Toy Fighter Netplay Savestate for freeplay mode

### ISSUE THREAD

**Issue by squeakyplushies** [blueminder/flycast-netplay-savestates#42]
[toyfight.state.net.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8335301/toyfight.state.net.zip)

As it says in the tin. Sorry it took so long to test/make.

**Comment by blueminder** [comment]
Thank you! Looks like it works well.

I will include this with the next batch of updates in a day or two. I have a new set of changes to version replay files so that old ones may be preserved. Once that's in, I'll include this state and close the ticket.

**Comment by blueminder** [comment]
It's in! Thank you.
