### ISSUE TITLE
SF Rush 2049 savestate

### ISSUE THREAD

**Issue by WatConcepts** [blueminder/flycast-netplay-savestates#45]
- All cheats unlocked.
- Battle Paint Shop and All Cars, Tracks, and Parts cheats are activated.
- Starts from the player select screen in 2-player mode.

[San Francisco Rush 2049 (USA) Net.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8965384/San.Francisco.Rush.2049.USA.Net.state.zip)

**Comment by blueminder** [comment]
Tested and added. Thank you!
