### ISSUE TITLE
Golf Shiyouyo 2 ~Aratanaru Chousen~ save state

### ISSUE THREAD

**Issue by ejcaruso** [blueminder/flycast-netplay-savestates#49]
This zip file contains a save state and lobby image for Golf Shiyouyo 2. Thanks in advance!

[Golf_Shiyou_yo_2_-_Aratanaru_Chousen_Japan.zip](https://github.com/blueminder/flycast-netplay-savestates/files/8987322/Golf_Shiyou_yo_2_-_Aratanaru_Chousen_Japan.zip)

**Comment by blueminder** [comment]
Tested and Added. I have given the lobby image to the Fightcade devs for the next update. Thank you!
