### ISSUE TITLE
 Gauntlet Legends (USA) save state - netplay

### ISSUE THREAD

**Issue by ValorZard** [blueminder/flycast-netplay-savestates#50]
this is what i got for now, please let me know if its wrong!
[Gauntlet_Legends_USA.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/9027902/Gauntlet_Legends_USA.state.zip)

**Comment by blueminder** [comment]
Tested and added as `Gauntlet Legends (USA).state.net`. Thank you!
