### ISSUE TITLE
Updated Golf Shiyou yo 2 ~Aratanaru Chousen~ save state

### ISSUE THREAD

**Issue by ejcaruso** [blueminder/flycast-netplay-savestates#69]
Updated save state where the second controller is actually connected. Lobby image is also included again for posterity.

[Golf_Shiyou_yo_2_-_Aratanaru_Chousen_Japan.zip](https://github.com/blueminder/flycast-netplay-savestates/files/9595881/Golf_Shiyou_yo_2_-_Aratanaru_Chousen_Japan.zip)

**Comment by blueminder** [comment]
Just updated the savestate. Thanks for your patience!

The next update will also automatically enable Left Thumbstick when it detects you are playing online. Enjoy!
