### ISSUE TITLE
shin nihon pro wrestling toukon retsuden 4 arcade edition, heavy metal Geomatrix, Virtua Tennis 1,Outtrigger

### ISSUE THREAD

**Issue by torao2** [blueminder/flycast-netplay-savestates#9]
[toukon4.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7496320/toukon4.state.zip)
[hmgeo.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7496348/hmgeo.state.zip)
[vtennis.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7496399/vtennis.state.zip)
[otrigger.state.zip](https://github.com/blueminder/flycast-netplay-savestates/files/7496425/otrigger.state.zip)

here are a few basic save states, see if they work.

**Comment by blueminder** [comment]
Tested and added. Thank you!
